package online.qsx.mapper;

import java.util.List;
import online.qsx.model.ResultModel;
import online.qsx.model.ResultModelCriteria;
import org.apache.ibatis.annotations.Param;

public interface ResultModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int countByExample(ResultModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int deleteByExample(ResultModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int insert(ResultModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int insertSelective(ResultModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    List<ResultModel> selectByExample(ResultModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") ResultModel record, @Param("example") ResultModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int updateByExample(@Param("record") ResultModel record, @Param("example") ResultModelCriteria example);
}