package online.qsx.mapper;

import java.util.List;
import online.qsx.model.StudentModel;
import online.qsx.model.StudentModelCriteria;
import org.apache.ibatis.annotations.Param;

public interface StudentModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int countByExample(StudentModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int deleteByExample(StudentModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int deleteByPrimaryKey(Integer studentno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int insert(StudentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int insertSelective(StudentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    List<StudentModel> selectByExample(StudentModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    StudentModel selectByPrimaryKey(Integer studentno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") StudentModel record, @Param("example") StudentModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int updateByExample(@Param("record") StudentModel record, @Param("example") StudentModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int updateByPrimaryKeySelective(StudentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    int updateByPrimaryKey(StudentModel record);
}