package online.qsx.model;

import java.io.Serializable;

public class GradeModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.GradeID
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    private Integer gradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.GradeName
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    private String gradename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grade
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.GradeID
     *
     * @return the value of grade.GradeID
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.GradeID
     *
     * @param gradeid the value for grade.GradeID
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.GradeName
     *
     * @return the value of grade.GradeName
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public String getGradename() {
        return gradename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.GradeName
     *
     * @param gradename the value for grade.GradeName
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void setGradename(String gradename) {
        this.gradename = gradename == null ? null : gradename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gradeid=").append(gradeid);
        sb.append(", gradename=").append(gradename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}