package online.qsx.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ResultModelCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public ResultModelCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStudentnoIsNull() {
            addCriterion("StudentNo is null");
            return (Criteria) this;
        }

        public Criteria andStudentnoIsNotNull() {
            addCriterion("StudentNo is not null");
            return (Criteria) this;
        }

        public Criteria andStudentnoEqualTo(Integer value) {
            addCriterion("StudentNo =", value, "studentno");
            return (Criteria) this;
        }

        public Criteria andStudentnoNotEqualTo(Integer value) {
            addCriterion("StudentNo <>", value, "studentno");
            return (Criteria) this;
        }

        public Criteria andStudentnoGreaterThan(Integer value) {
            addCriterion("StudentNo >", value, "studentno");
            return (Criteria) this;
        }

        public Criteria andStudentnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("StudentNo >=", value, "studentno");
            return (Criteria) this;
        }

        public Criteria andStudentnoLessThan(Integer value) {
            addCriterion("StudentNo <", value, "studentno");
            return (Criteria) this;
        }

        public Criteria andStudentnoLessThanOrEqualTo(Integer value) {
            addCriterion("StudentNo <=", value, "studentno");
            return (Criteria) this;
        }

        public Criteria andStudentnoIn(List<Integer> values) {
            addCriterion("StudentNo in", values, "studentno");
            return (Criteria) this;
        }

        public Criteria andStudentnoNotIn(List<Integer> values) {
            addCriterion("StudentNo not in", values, "studentno");
            return (Criteria) this;
        }

        public Criteria andStudentnoBetween(Integer value1, Integer value2) {
            addCriterion("StudentNo between", value1, value2, "studentno");
            return (Criteria) this;
        }

        public Criteria andStudentnoNotBetween(Integer value1, Integer value2) {
            addCriterion("StudentNo not between", value1, value2, "studentno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoIsNull() {
            addCriterion("SubjectNo is null");
            return (Criteria) this;
        }

        public Criteria andSubjectnoIsNotNull() {
            addCriterion("SubjectNo is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectnoEqualTo(Integer value) {
            addCriterion("SubjectNo =", value, "subjectno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoNotEqualTo(Integer value) {
            addCriterion("SubjectNo <>", value, "subjectno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoGreaterThan(Integer value) {
            addCriterion("SubjectNo >", value, "subjectno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("SubjectNo >=", value, "subjectno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoLessThan(Integer value) {
            addCriterion("SubjectNo <", value, "subjectno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoLessThanOrEqualTo(Integer value) {
            addCriterion("SubjectNo <=", value, "subjectno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoIn(List<Integer> values) {
            addCriterion("SubjectNo in", values, "subjectno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoNotIn(List<Integer> values) {
            addCriterion("SubjectNo not in", values, "subjectno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoBetween(Integer value1, Integer value2) {
            addCriterion("SubjectNo between", value1, value2, "subjectno");
            return (Criteria) this;
        }

        public Criteria andSubjectnoNotBetween(Integer value1, Integer value2) {
            addCriterion("SubjectNo not between", value1, value2, "subjectno");
            return (Criteria) this;
        }

        public Criteria andExamdateIsNull() {
            addCriterion("ExamDate is null");
            return (Criteria) this;
        }

        public Criteria andExamdateIsNotNull() {
            addCriterion("ExamDate is not null");
            return (Criteria) this;
        }

        public Criteria andExamdateEqualTo(Date value) {
            addCriterion("ExamDate =", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateNotEqualTo(Date value) {
            addCriterion("ExamDate <>", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateGreaterThan(Date value) {
            addCriterion("ExamDate >", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateGreaterThanOrEqualTo(Date value) {
            addCriterion("ExamDate >=", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateLessThan(Date value) {
            addCriterion("ExamDate <", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateLessThanOrEqualTo(Date value) {
            addCriterion("ExamDate <=", value, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateIn(List<Date> values) {
            addCriterion("ExamDate in", values, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateNotIn(List<Date> values) {
            addCriterion("ExamDate not in", values, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateBetween(Date value1, Date value2) {
            addCriterion("ExamDate between", value1, value2, "examdate");
            return (Criteria) this;
        }

        public Criteria andExamdateNotBetween(Date value1, Date value2) {
            addCriterion("ExamDate not between", value1, value2, "examdate");
            return (Criteria) this;
        }

        public Criteria andStudentresultIsNull() {
            addCriterion("StudentResult is null");
            return (Criteria) this;
        }

        public Criteria andStudentresultIsNotNull() {
            addCriterion("StudentResult is not null");
            return (Criteria) this;
        }

        public Criteria andStudentresultEqualTo(Integer value) {
            addCriterion("StudentResult =", value, "studentresult");
            return (Criteria) this;
        }

        public Criteria andStudentresultNotEqualTo(Integer value) {
            addCriterion("StudentResult <>", value, "studentresult");
            return (Criteria) this;
        }

        public Criteria andStudentresultGreaterThan(Integer value) {
            addCriterion("StudentResult >", value, "studentresult");
            return (Criteria) this;
        }

        public Criteria andStudentresultGreaterThanOrEqualTo(Integer value) {
            addCriterion("StudentResult >=", value, "studentresult");
            return (Criteria) this;
        }

        public Criteria andStudentresultLessThan(Integer value) {
            addCriterion("StudentResult <", value, "studentresult");
            return (Criteria) this;
        }

        public Criteria andStudentresultLessThanOrEqualTo(Integer value) {
            addCriterion("StudentResult <=", value, "studentresult");
            return (Criteria) this;
        }

        public Criteria andStudentresultIn(List<Integer> values) {
            addCriterion("StudentResult in", values, "studentresult");
            return (Criteria) this;
        }

        public Criteria andStudentresultNotIn(List<Integer> values) {
            addCriterion("StudentResult not in", values, "studentresult");
            return (Criteria) this;
        }

        public Criteria andStudentresultBetween(Integer value1, Integer value2) {
            addCriterion("StudentResult between", value1, value2, "studentresult");
            return (Criteria) this;
        }

        public Criteria andStudentresultNotBetween(Integer value1, Integer value2) {
            addCriterion("StudentResult not between", value1, value2, "studentresult");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table result
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 22 14:57:06 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}