package online.qsx.model;

import java.io.Serializable;
import java.util.Date;

public class ResultModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result.StudentNo
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    private Integer studentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result.SubjectNo
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    private Integer subjectno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result.ExamDate
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    private Date examdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result.StudentResult
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    private Integer studentresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result.StudentNo
     *
     * @return the value of result.StudentNo
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public Integer getStudentno() {
        return studentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result.StudentNo
     *
     * @param studentno the value for result.StudentNo
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void setStudentno(Integer studentno) {
        this.studentno = studentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result.SubjectNo
     *
     * @return the value of result.SubjectNo
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public Integer getSubjectno() {
        return subjectno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result.SubjectNo
     *
     * @param subjectno the value for result.SubjectNo
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void setSubjectno(Integer subjectno) {
        this.subjectno = subjectno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result.ExamDate
     *
     * @return the value of result.ExamDate
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public Date getExamdate() {
        return examdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result.ExamDate
     *
     * @param examdate the value for result.ExamDate
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void setExamdate(Date examdate) {
        this.examdate = examdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result.StudentResult
     *
     * @return the value of result.StudentResult
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public Integer getStudentresult() {
        return studentresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result.StudentResult
     *
     * @param studentresult the value for result.StudentResult
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    public void setStudentresult(Integer studentresult) {
        this.studentresult = studentresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Wed Nov 22 14:57:06 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentno=").append(studentno);
        sb.append(", subjectno=").append(subjectno);
        sb.append(", examdate=").append(examdate);
        sb.append(", studentresult=").append(studentresult);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}